### ISSUE TITLE
Contrary to text, MP3Importer class seems to have a 'has many' relationship w/ Song class

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/ruby-collaborating-objects-readme#11]
From README.md: 

> In fact, the classes do not even need to have any relationship ("has many" or "belongs to") to collaborate. Imagine we have an MP3 Importer that is responsible for taking in a bunch of MP3 files and making a song for each unique filename.
> .
> .
> .
> 
> ``` ruby
> class MP3Importer
> attr_accessor :songs 
>   def import(list_of_filenames)
>     list_of_filenames.each{|file_name| songs << Song.new_by_filename(file_name)}
>   end
> end
> ```

Maybe I'm missing something, but it seems like the `MP3Importer` class has a 'has many' relationship with the `Song` class. I understand that the 'real-world model' of an MP3 importer doesn't have that type of relationship with the MP3 files that it imports, but, by storing all of the imported `Song` objects in a `@songs` array within each `MP3Importer` object, it certainly seems to have that type of relationship here.

Perhaps use the `MP3Importer` class as only a factory for new `Song` objects from a passed-in list, without storing the values in `@songs`?

/pedantic

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by gj** [comment]
Also, the closing bit didn't make a lot of sense to me –– weren't the previous lessons all about collaboration between directly-related objects, such as `Artist` and `Song` (or `Author` and `Post`)?

> This should then return the new Artist object that was created by the #artist_name method. **This is just another example of how objects can collaborate without being directly related**.
